version: "3.7"
services:
  api_service:
    container_name: api_core
    build: "./core"
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - maria_db
    environment:
      DB_HOST: maria_db
      DB_PORT: 3306
  maria_db:
    container_name: maria_db
    image: "mariadb:10.5.8"
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: ifeed